version: "3"
services:
  app:
    image: ${APP_DEV_IMAGE}
    env_file:
      - .env.local
    volumes:
      - ./:/srv/app
      - ./.dev.php.ini:/usr/local/etc/php/conf.d/dev.ini
    ports:
      - 443:443
    networks:
      - netapp
  db_postgres:
    image: postgres:13
    env_file:
      - .env.local
    ports:
      - 5432
    networks:
      - netapp
networks:
  netapp:
