version: "3"
services:
  app:
    image: ${APP_DEV_IMAGE}
    env_file:
      - .env.local
    volumes:
      - ./:/srv/app
    ports:
      - 443:443
    networks:
      - netapp
networks:
  netapp:
